Quality Report display
mitre/ecqm-frontend pull request #10
Opened 2016-09-09 13:56 UTC by eedrummer

This PR cleans up the display of quality reports.

- Reports no longer wrap around the measure title
- Results now in a bootstrap panel with the measure title as the header
- Measure description now displayed
- FA icons depending on measure type (proportion, episode of care, CV)
- Table to display population counts
- Proper display of CV measure results
- Doughnut chart for result display

2016-09-14 21:18 UTC, noranda commented on test/components/measure_category_test.js
> +    component.find(".individual").first().simulate("click");
Should there be an `expect` here?

2016-09-14 21:21 UTC, noranda commented on test/reducers/measures_test.js
> +  it('should flatten categories', () => {
This test is failing for me:

```  1) Measure reducers should flatten categories:
     TypeError: categories.includes is not a function
      at src/reducers/measures.js:25:22
      at Array.forEach (native)
      at flattenCategories (src/reducers/measures.js:24:12)
      at Context.<anonymous> (test/reducers/measures_test.js:10:24)```

2016-09-14 21:22 UTC, noranda requested changes

2016-09-14 22:40 UTC, eedrummer commented on test/components/measure_category_test.js
> +    component.find(".individual").first().simulate("click");
The expect is in the onAddMeasure

2016-09-14 22:58 UTC, eedrummer commented on test/reducers/measures_test.js
> +  it('should flatten categories', () => {
I doubt this is the case, but this PR modifies the package.json. Maybe try an npm install?

2016-09-15 13:49 UTC, eedrummer commented
@noranda I've rebased this for a cleaner git history. I've rerun the tests locally and they pass for me. They also pass on Travis. Have you been able to get them to pass on your system?

2016-09-15 14:47 UTC, noranda commented on test/reducers/measures_test.js
> +  it('should flatten categories', () => {
I have tracked down the issue. The problem is that I'm using the stable version of node (4.5.0), but node doesn't support `includes` until version 6 (current is 6.5.0). This is the function in question in `/src/reducers/measures.js`:

```
export function flattenCategories(measures) {
  let categories = [];
  measures.forEach((m) => {
    if (! categories.includes(m.category)) {
      categories.push(m.category);
    }
  });
  return categories.sort();
}
```

While anyone using the current node version would be fine with this, I'd suggest changing `! categories.includes(m.category)` to `categories.indexOf(m.category) === -1` in order to handle users (like me) who are using the older stable node version.

2016-09-15 15:02 UTC, eedrummer commented on test/reducers/measures_test.js
> +  it('should flatten categories', () => {
Done.

2016-09-15 15:13 UTC, noranda approved these changes

2016-09-15 15:14 UTC, merged